### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by jayflo** [AtomLinter/linter-scalac#12]
I am having trouble getting any output from this linter.  Here are the specs:
OS: Windows 8.1
Atom: 0.199.0 (also did not work for 0.198.0)

`config.cson`

```
"*":
  "exception-reporting":
    userId: "28f1a3f3-efad-7770-3410-dfbc991a22b9"
  welcome:
    showOnStartup: false
  core:
    destroyEmptyPanes: false
    disabledPackages: [
      "language-mustache"
      "archive-view"
      "autosave"
      "image-view"
      "language-perl"
      "language-php"
      "tabs"
      "tree-view"
      "highlight-selected"
    ]
  editor:
    fontFamily: "Source Code Pro"
    scrollPastEnd: true
  whitespace:
    ensureSingleTrailingNewline: false
  tabs:
    showIcons: true
  "tree-view":
    hideVcsIgnoredFiles: false
    hideIgnoredNames: false
    showOnRightSide: false
    sortFoldersBeforeFiles: true
  linter:
    statusBar: "Show error of the selected line"
  "linter-scalac":
    scalacExecutablePath: "C:\\Program Files (x86)\\scala\\bin"
  "autocomplete-plus":
    confirmCompletion: "tab"
    backspaceTriggersAutocomplete: true
    autoActivationDelay: 0
```

`.classpath` (in project root)

```
C:\Users\Jaret\Documents\projects\fpscala\target\scala-2.10\classes;C:\Users\Jaret\.sbt\boot\scala-2.10.4\lib\scala-library.jar
```

I should point out that :

1) The console does not output any errors, just

```
activate linter-scalac  ...  C:\Users\Jaret\.atom\packages\linter-scalac\lib\init.coffee:8 
Window load time: 2365ms  ...  index.js:52
```

2) I am able to get the jshint linter to work...so I am not quite sure where to go from here.

**Comment by monapasan** [comment]
Same here: Windows 7.  Atom 1.0.19 .

**Comment by k2b6s9j** [comment]
Please add the compiler executable to `scalacExecutablePath`, or if it's in your PATH empty the configuration value.

**Comment by monapasan** [comment]
@k2b6s9j  Doesn't solve the problem.
```
  "linter-scalac":
    scalacExecutablePath: "C:\\Program Files (x86)\\scala\\bin\\scalac"
    scalacOptions: "-Xlint"
// i was also trying "C:\\Program Files (x86)\\scala\\bin\\scalac.bat"
```
it works from console, but somehow nothing happens in atom...

**Comment by Arcanemagus** [comment]
@jayflo or @monapasan are you still having issues?

**Comment by cvakiitho** [comment]
@Arcanemagus I confirm the issue exists in fresh install of atom + linter + linter-scalac with scalac in path on windows 7 x64.

**Comment by andystanton** [comment]
@cvakiitho does the problem persist if you specify `scalacExecutablePath` as suggested here https://github.com/AtomLinter/linter-scalac/issues/12#issuecomment-147711532 

Also, I don't know if it's the same with Windows, but on OSX in order for Atom to pick up my environment variables, I have to launch it from the terminal rather than shortcut.

**Comment by cvakiitho** [comment]
Added `C:\Program Files (x86)\scala\bin\` into Scalac Executable Path in package settings - restarted, still not linting.

**Comment by andystanton** [comment]
You'd need to set the path so that includes `scalac` i.e. `C:\Program Files (x86)\scala\bin\scalac`. 

If that doesn't help, it's possible the space in the path is causing problems. That's the only difference with the [automated Windows spec job](https://github.com/AtomLinter/linter-scalac/blob/master/appveyor.yml), other than the version of Windows.

**Comment by cvakiitho** [comment]
@andystanton Thanks! scalac is needed indeed. Work fine now. 

Side note, scalac linter works only if you have whole project open right? Otherwise it woun't have project paths?

**Comment by andystanton** [comment]
@cvakiitho that's great!

You can lint a single file as long as it doesn't have external dependencies but the recommendation is that you create a `.classpath` file ([documentation](https://github.com/AtomLinter/linter-scalac#classpath)).
