### ISSUE TITLE
Uses .jar file as CWD

### ISSUE THREAD

**Issue by fgeldenhuys** [AtomLinter/linter-scalac#15]
If you have a .classpath file with the first entry being a .jar file, scalac-linter tries to use that as the PWD and the exec call to scalac fails with ENOTDIR. My current workaround is just to change:
```
exec(command, cwd: @cwd, (error, stdout, stderr) => if stderr then @processMessage(stderr, callback))
```
to
```
exec(command, cwd: '~', (error, stdout, stderr) => if stderr then @processMessage(stderr, callback))
```
in linter-scalac.coffee

**Comment by fgeldenhuys** [comment]
OK I see I need to actually change the order of the dirs/jars listed in .classpath so that the classes output dir is first.

**Comment by andystanton** [comment]
Are you happy with making sure the classes output comes first @fgeldenhuys? If so, I'll close this ticket.

**Comment by fgeldenhuys** [comment]
Sure thanks, go ahead.

**Comment by andystanton** [comment]
👍
