### ISSUE TITLE
Automatic detection of classpath

### ISSUE THREAD

**Issue by rockymadden** [AtomLinter/linter-scalac#2]
Assuming that SBT can be relied upon as a hard dependency, this could be done. For a standard SBT project, it's a no brainer but for some of the more complex scenarios it gets a little tough. Another possibility would be per-project settings in Atom, however that is not yet implemented.

**Comment by hawkw** [comment]
> Assuming that SBT can be relied on as a hard dependency

I'm not a fan of this assumption – I've worked on a couple of Scala projects which used Gradle for managing builds. It would be nice if the linter plugin would remain usable for Scala projects not using SBT.

**Comment by MasseGuillaume** [comment]
@hawkw it could support both.

**Comment by hawkw** [comment]
I'd love to see support for both – probably should support Maven as well, I'm sure somebody somewhere is using Maven to build Scala projects. Of course, I'm sure SBT is the most common and it ought to be prioritised. I just think it's important that the plugin not break if SBT isn't being used.

**Comment by k2b6s9j** [comment]
I think this is outside the scope of this project. If you're using SBT, Gradle, or Maven as your build solution you should be using a linter built for that solution. Thankfully, those three are on my list of linters to implement, and will do so once we finish the transition to the new Linter API.

**Comment by k2b6s9j** [comment]
However, because this is not my project I will leave it open.

**Comment by Arcanemagus** [comment]
It sounds like this is a perfect candidate for what I'm assuming @kepler0 is talking about: https://github.com/noseglid/atom-build

However, I'm not personally familiar with this either, so I'll leave it to @andystanton to close this issue if I'm wrong.

**Comment by andystanton** [comment]
Yep, and there's an Atom package that already makes use of build: https://atom.io/packages/build-sbt
