### ISSUE TITLE
Does not detect classpath

### ISSUE THREAD

**Issue by pbnsilva** [AtomLinter/linter-scalac#22]
Hi,

linter-scalac is showing me errors like this:

`error writing class MyClass: ./com/mycom/myproject/core/MyClass.class: ./com is not a directory`

Looks like my `.classpath` is not being detected? Any ideas?

Thanks

**Comment by laughedelic** [comment]
I have the same problem

**Comment by pbnsilva** [comment]
Did a quick investigation and the classpath is not the problem. I'll close as the title is no longer relevant.
Will do a better investigation when I have some time.
