### ISSUE TITLE
Prevent lint from polluting project with class files

### ISSUE THREAD

**Issue by dotboris** [AtomLinter/linter-scalac#24]
Whenever the linter runs and there are no errors, it leaves a bunch of class files in the project. I would like for this not to happen.

From my understanding this is because running `scalac -Xlint` still compiles the code and writes out `*.class` files.

I've done a little bit of looking around and it seems like you can't force scalac not to generate `*.class` files.It is possible to pass the `-d` flag to specify where the `*.class` files will be put.

I suggest to add `-d /tmp/???` or something similar (and probably cross platform) to the default flags.

**Comment by andystanton** [comment]
Hi @beraboris 

I added the ability to compile classes to the path specified in the [.classpath file](https://github.com/AtomLinter/linter-scalac#classpath) in PR #23. Assuming you choose a classpath that isn't the project root (e.g. /path/to/project/target/scala-2.11/classes) this will keep the .class files out of your project root.

Does that help with your issue?

**Comment by dotboris** [comment]
@andystanton I just tried this and it solves my problem perfectly. Thanks a bunch!

**Comment by andystanton** [comment]
Great, closing this issue @dotboris.
