### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ilanbiala** [AtomLinter/linter-scalac#3]
It would be great to have a changelog.md which tells users what updates contain API changes, bug fixes, performance changes, etc.

**Comment by ilanbiala** [comment]
@dmnd status? Is this going to happen, or should I just close?

**Comment by hd-deman** [comment]
@ilanbiala It's better to use [releases](https://github.com/AtomLinter/linter-scalac/releases) for change log

**Comment by ilanbiala** [comment]
Also no changelog here in the releases...so yeah.
