### ISSUE TITLE
No project paths available

### ISSUE THREAD

**Issue by molsky** [AtomLinter/linter-scalac#38]
Installed Scala to OS X via brew command. After that installed language-scala and linter-scalac plugin for Atom. For some reason this plugin can't find path to scalac bin.
Tried to configure path to plugins settings but still same error. 
`which scalac` gives following path `/usr/local/bin/scala` and from command line scala and scalac commads works fine.
Tried also `/usr/local/Cellar/scala/2.11.7/bin/scalac` but that doesn't help either.

Atom 1.4.1
OS X 10.10.5
Scala 2.11.7

**Comment by Arcanemagus** [comment]
What is the _exact_ error you are seeing?

**Comment by molsky** [comment]
<img width="1390" alt="errors" src="https://cloud.githubusercontent.com/assets/1943521/12628868/e6f442c4-c54d-11e5-9c18-5ccaf9ef7893.png">
And at the moment those comes when saving scala file. Tested a little more and after creating new Scala file and doing something there linter works without any errors.
<img width="657" alt="working" src="https://cloud.githubusercontent.com/assets/1943521/12629027/9a9dd4de-c54e-11e5-83dd-1f454f89e019.png">
Closed Atom, opened it again and opened recent Scala file and again `No project paths available`

**Comment by Arcanemagus** [comment]
`No project paths available` is an entirely different error from not being able to find `scalac` :wink:.

Does `scalac -Xlint foo.scala` from the command line on the file where that error is showing show correct results, or the same thing?

**Comment by molsky** [comment]
Running that from command line works fine.
![atom](https://cloud.githubusercontent.com/assets/1943521/12639228/9df323a2-c5ab-11e5-8632-94960f033db2.png)

**Comment by andystanton** [comment]
I had to specifically load a non-existent path such as the one shown in the screenshots (atom://config) by opening my Atom config through the menu options.

Steps to reproduce:

1. Load Atom.
2. Atom -> Open your config
3. File -> New file
4. File -> Save as
5. Location: anywhere, Filename: foo.scala
6. Save

This appears to have been fixed during the migration from CoffeeScript to Javascript though it's unclear why.

* [Original CS](https://github.com/AtomLinter/linter-scalac/blob/9425acc50a5ca980668ee89ceb20d907bb81f39e/lib/linter-scalac.coffee#L59-L60)
* [New JS](https://github.com/andystanton/linter-scalac/blob/c728ae173397c8232cedd8159f44f6e9761d1ab7/lib/linter-scalac.js#L86-L89)

I'll try and understand why it's fixed, then get the change merged. In the meantime, I suggest creating and modifying Scala source in the context of a real path on the file system.

**Comment by andystanton** [comment]
Oh wait, it's totally clear why it's fixed. I missed the end regex match during the migration. Oops, time for a unit test.

**Comment by andystanton** [comment]
Hi @molsky 

I've released a fix in v1.4.0. Can you update linter-scalac to this version and try to replicate your issue?

**Comment by molsky** [comment]
Updated and now it works, thanks.

**Comment by andystanton** [comment]
Great!
