### ISSUE TITLE
pointing linter-scalac to my lib/ directory

### ISSUE THREAD

**Issue by untra** [AtomLinter/linter-scalac#54]
I have a `lib` folder in my project directory that contains jars that get imported when I compile and run my scala project. How can I point the linter towards this directory?

At the moment, it fails to find these jars, and the linter marks almost every line as an error. Is this a configuration item I should be passing in through the linter settings? How do I set this?

Thanks for your help!

**Comment by andystanton** [comment]
Hi @untra,

Is the project sbt based? If so, you can follow the instructions here: https://github.com/AtomLinter/linter-scalac#classpath

Otherwise you can create your own .classpath file with the following format:

```
/path/to/project/target/scala-2.11/classes:/path/to/project/libs/foo.jar:/path/to/project/libs/bar.jar
```

**Comment by untra** [comment]
The project is not sbt based.

I found the full classpath. It was in my `target` directory. I made a symlink to it in our root directory, which should help with the linting. It still doesn't recognize files in the same package, but it's close enough for what we need.

Thanks!
